config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users

  resources :venues, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [ :new, :create ]
    resources :bookings, only: [ :new, :create ]
  end
  resources :pages, only: [:home]
  resources :reviews, only: [ :destroy ]
  resources :bookings, only: [ :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :venue
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :venue
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
include Gravtastic
gravtastic

  has_many :venues
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_venue,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }

#def self.show(id)
 # if show
  #  where(["name LIKE ?","%#{show}%"])
  #else
  #  all
  #end
#end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
include Pundit

 # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @venue = Venue.find(params[:venue_id])
    @user = current_user
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @venue = Venue.find(params[:venue_id])
    @user = current_user
    @booking.venue = @venue
    @booking.user = @user
    if @booking.save
      render 'shared/booking_confirmation'
    else
      render 'venues/show'
    end
  end
  def index
    @bookings = current_user.bookings
  end


private
 def booking_params
   params.require(:booking).permit(:date)
 end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

 def home
  random_venue = rand(Venue.count)
  @venues = Venue.offset(random_venue).limit(9)
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   def new
    @venue = Venue.find(params[:venue_id])
    @review = Review.new
  end

   def create
    @review = Review.new(review_params)
    @venue = Venue.find(params[:venue_id])
    @review.venue = @venue
    if @review.save
      redirect_to venue_path(@venue)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to venue_path(@review.venue)
  end
  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @venue = Venue.new # needed to instantiate the form_for
  end

   def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render 'new'
    end
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :address, :description, :price, :picture_url)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  def index
    @venues = Venue.geocoded # returns flats with coordinates
    if params[:query].present?
    @venues = @venues.search_by_venue(params[:query])
    end


    @markers = @venues.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude
      }
      @venues = policy_scope(@venues)
    end
  end

  #def search
  #@venues = Venue.includes(params[:name])
  #end

  def new
    @venue = Venue.new
    authorize @venue
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    authorize @venue
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.new
    @reviews = Review.where(venue_id: params[:id])
    @markers = [{  lat: @venue.latitude, lng: @venue.longitude }]


  end

  def edit
  end

  def update
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  def destroy
    @venue.destroy
    redirect_to venues_path
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
    authorize @venue
  end

  def venue_params
    params.require(:venue).permit(:name, :address, :description, :photo, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<head>
  <link rel="stylesheet" href="_booking.scss">
</head>

<% @bookings.each do |booking| %>
</br> </br>
<div class="card-product">
    <% venue = booking.venue %>
      <% if venue.photo.attached? %>
        <%= cl_image_tag  venue.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  <div class="card-product-infos">
    <h2> <%= venue.name %></h2>
    <p> <%= booking.price %> </p>
    <%= link_to "View listing", venue_path(venue) %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceFinding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>



  </head>

  <body>


    <%#= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.picsum.photos/id/158/4836/3224.jpg);">
  <div class="container">
    <h1>Rent a venue for any type of event at your convenience with one click.</h1>
    <a class="btn btn-success btn-lg text-white" id="abc" href="/venues">Check out all venues!</a>
  </div>
</div>

<div class="cards" href="/venues">

<% @venues.each do |venue| %>

<a href="<%= venue_path(venue)%>">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3),
    rgba(0,0,0,0.3)), url(<%= cl_image_path venue.photo.key%>)">
    <p> <%= venue.name %></p>
  </div>
</a>


<% end %>

app/views/reviews/new.html.erb
<div class="review-form" align="center">
  <h3>Review <%= @venue.name %></h3>
  <br/><br/>
  <%= simple_form_for [ @venue, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: 0..5 %>
    <%= f.submit "Submit review", class: "btn btn-primary"%>
<% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Yess
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for(@venue) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <img src="https://cdn.clipart.email/58c5b00890a38cfddb75a7eb1cfbd52a_shrink-url-png-picture-836572-shrink-url-png_512-512.png">
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <form class="form-inline my-2 my-lg-0">



      </form>

      <% if user_signed_in? %>
       <li class="nav-item mx-0 my-3">
          <%= link_to "Home", "/", class: "navbar-link text-white" %>
        </li>
        <li class="nav-item mx-0 my-3">
          <%= link_to "Add Venue", "venues/new", class: "navbar-link text-white  mx-2" %>
        </li>
        <li class="nav-item mx-0 my-3">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-link text-white  mx-2" %>
        </li>
        <li class="nav-item mx-0 my-3">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => "navbar-link text-white  mx-2" %>
        </li>
        <li class="nav-item mx-0 my-3">
          <%= link_to "Book", "/bookings", class: "navbar-link text-white  mx-2" %>
        </li>
         <li class="nav-item mx-0 my-3">
          <%= image_tag current_user.gravatar_url, :class => "gravatar" %>
        </li>

          </div>

      <% else %>
        <li class="nav-item mx-0 my-3">
          <%= link_to "Login", new_user_session_path, class: "navbar-link text-white" %>
        </li>
        <li class="nav-item mx-0 my-3">
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link text-white'  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/booking_confirmation.html.erb
<div id="card">
  <h3>Congratulations on your booking!</h3>
  <p>We will send you an email with more details nearer to the event.</p>
  <a class="btn btn-flat" id="abc" href="/bookings">My bookings </a>
</div>

app/views/venues/_form.html.erb
<div class="create-form" >

<%= simple_form_for(@venue) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
   <%= f.input :capacity %>
  <%= f.input :photo, as: :file%>

  <div class="create-btn" >
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

</div>

app/views/venues/edit.html.erb
<%= render "form", venue: @venue %>

app/views/venues/index.html.erb
  <div class="search-bar">
    <%= form_tag venues_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a venue"
    %>
    <div class="search-btn">
      <%= submit_tag "Search", class: "btn btn-success mx-2 text-white" %>
      <% end %>
    </div>
  </div>

<head>
  <link href="https://fonts.googleapis.com/css2?family=Bitter&display=swap" rel="stylesheet">
</head>

<body>
 <div class="listing-header">
   <h5>Showing <%= @venues.count %> event venues </h5>
 </div>
<div class="container">
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  </div>
   <div class="row"></div>
   <div class="listings-list d-flex flex-wrap m-5">
      <% @venues.each do |venue| %>
          <div class="card-listing m-3">
            <% if venue.photo.attached? %>
             <%= cl_image_tag venue.photo.key, height: 300, width: 400, crop: :fill %>
             <% end %>
              <br><br>
              <div class="card-listing-infos">
                <h2> <%= venue.name %> </h2>
                 <br /><br />
                <p> <%= venue.address %> </p>
                <p> Capacity : <%= venue.capacity %> </p>
                 <br /><br />
                <h2 class="card-listing-link"><%= link_to 'View Venue', venue_path(venue) %>
                  <% if policy(venue).edit? %>
                <%= link_to 'Edit', edit_venue_path(venue), class: 'ml-3 text-warning' %>
                <%= link_to "Remove", venue_path(venue),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: 'ml-3 text-danger'
              %>
                <% end %>
              </h2>

              </div>
          </div>
      <% end %>
  </div>
</body>

app/views/venues/new.html.erb
<%= render "form", venue: @venue %>

app/views/venues/show.html.erb
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" id="carousel" style="height: 500px">
        <div class="carousel-item active">
            <img class="d-block w-100" src=" <%= cl_image_path @venue.photo.key %> " alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://res.cloudinary.com/dthacgw4y/image/upload/v1589043147/image_tcphz4.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/nature" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container margin-top-negative" id="card">
  <div class="row">
    <div class="col-8">
      <div class="venue-show-card">
        <div id="name">
          <h1><%= @venue.name %></h1>
        </div>
         <div id="address">
           <h6>Location</h6>
          <p><%= @venue.address %></p>
        </div>
      </div>
      <div class="venue-show-card">
        <div id="description">
          <h6>Description</h6>
          <p><%= @venue.description %></p>
        </div>
      </div>
      <h6>Amenities</h6>
    </br> </br>
      <div class= "icons">
      <i class="fas fa-wifi"></i>
      <i class="fas fa-utensils"></i>
      <i class="fas fa-swimming-pool"></i>
      <i class="fas fa-fan"></i>
      <i class="fas fa-cocktail"></i>
      <i class="fas fa-tree"></i>
      <i class="fas fa-bed"></i>
      <i class="fas fa-tv"></i>

    </div>
      <div class= buttons-flex>
      <div id= listing-button> <button type="button" class="btn btn-outline-secondary">MAP LOCATION</button> </div>
      <div id= listing-button> <button type="button" class="btn btn-outline-secondary">PHOTOS</button> </div>
      </div>
    </div>

<div class="col-4">
  <div class="venue-show-card">
    <h5>Book this place!</h5>
    <div class= "input-group" >
        <%= simple_form_for([@venue, @booking]) do |f| %>
    <%= f.input :date %>
    <%= f.submit "Book ",
     class: "btn btn-warning mt-2" %>  <% end %>
     </div>
  </div>



 <div class="venue-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons mr-2">Capacity</i><span><%= "#{@venue.capacity} guests" %></span>
          </div>

          <div class="flex ml-3">
            <i class="material-icons mr-2"> <%= @venue.price %> $ </i>
          </div>
        </div>
      </div>

<div class="venue-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fab fa-facebook-square fa-2x mr-2"></i>
            <i class="fab fa-twitter-square fa-2x mr-2"></i>
            <i class="fab fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
     </div>
  </div>
  </div>

 <div class="list-group">
        <% @reviews.each do |review| %>
          <li class="list-group-item">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
          </li>
        <% end %>
      </div>

    </div>
     <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>